### PR TITLE
Update to Normalize v4.0.0

### PR DESCRIPTION
**Pull request by tysongach**

### CODE REVIEW

**Comment by brendon** [comment]
Fixes #17. @markmcconachie are you happy for me to merge this? I was able to convince the normalise project to release a new version.

**Comment by markmcconachie** [comment]
@brendon Sure, I can add you as an owner on rubygems too if you want?

**Comment by tysongach** [comment]
Thanks!

**Comment by markmcconachie** [comment]
Thanks for the contribution @tysongach :)

**Comment by brendon** [comment]
Thanks @markmcconachie :) That sounds good to me. Are there any special instructions for deploying the gem?

**Pull request merged**
