### PR TITLE
gem version matches normalize css version

### PR DESCRIPTION
**Pull request by tomichj**
Syncing the normalize-rails version to match the normalize css version (6.0.0).

### CODE REVIEW

**Comment by brendon** [comment]
This would normally be done when a gem is released. @markmcconachie, are you good to release 6.0.0?

**Comment by brendon** [comment]
Hmmm. No response. Not sure what I can do from here unfortunately.

**Comment by markmcconachie** [comment]
@paulbeattie is taking over this project/repo. @paulbeattie

**Comment by brendon** [comment]
Thanks Mark :) Good to hear from you again. Add me as a gem publisher also if you like. You've already added me as a contributor.

**Comment by markmcconachie** [comment]
Yes sorry for the lack of response, I  have not been using github for quite some time.
@paulbeattie can you add @brendon as a contributor?

If he doesn't then I will. I just don't have rubygems setup right now (I have not done rails development for years now)

**Comment by markmcconachie** [comment]
@paulbeattie

**Comment by markmcconachie** [comment]
@paulbeattie

**Comment by paulbeattie** [comment]
Isn't there a way to transfer on GitHub? Happy enough to add as a gem maintainer, is it just the email on your profile @brendon ?

**Comment by brendon** [comment]
Thanks @paulbeattie. The email is brendon@spike.net.nz. :)

**Pull request closed without merging**
